safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Soton Sailing Robot"
description: "A student led team building next generation open source ocean observation platforms."
baseurl: "/blog"
url: "http://www.sotonsailrobot.org" # replace by your site's url
twitter_username: SotonSailRobot
github_username:  Maritime-Robotics-Student-Society # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Yu Cao"
address: "B176 Boldrewood Campus,  University of Southampton, U.K"
email: "sotonsailrobot@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
